/**
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.dsl.impl;

import io.entitas.lang.dsl.Alias;
import io.entitas.lang.dsl.AliasList;
import io.entitas.lang.dsl.DslPackage;
import io.entitas.lang.dsl.SingleAlias;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Alias</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.entitas.lang.dsl.impl.AliasImpl#getName <em>Name</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.impl.AliasImpl#getListOfAliases <em>List Of Aliases</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.impl.AliasImpl#getSingleAlias <em>Single Alias</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AliasImpl extends MinimalEObjectImpl.Container implements Alias
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getListOfAliases() <em>List Of Aliases</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListOfAliases()
   * @generated
   * @ordered
   */
  protected AliasList listOfAliases;

  /**
   * The cached value of the '{@link #getSingleAlias() <em>Single Alias</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSingleAlias()
   * @generated
   * @ordered
   */
  protected SingleAlias singleAlias;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AliasImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.ALIAS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.ALIAS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AliasList getListOfAliases()
  {
    return listOfAliases;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetListOfAliases(AliasList newListOfAliases, NotificationChain msgs)
  {
    AliasList oldListOfAliases = listOfAliases;
    listOfAliases = newListOfAliases;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.ALIAS__LIST_OF_ALIASES, oldListOfAliases, newListOfAliases);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setListOfAliases(AliasList newListOfAliases)
  {
    if (newListOfAliases != listOfAliases)
    {
      NotificationChain msgs = null;
      if (listOfAliases != null)
        msgs = ((InternalEObject)listOfAliases).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.ALIAS__LIST_OF_ALIASES, null, msgs);
      if (newListOfAliases != null)
        msgs = ((InternalEObject)newListOfAliases).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.ALIAS__LIST_OF_ALIASES, null, msgs);
      msgs = basicSetListOfAliases(newListOfAliases, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.ALIAS__LIST_OF_ALIASES, newListOfAliases, newListOfAliases));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SingleAlias getSingleAlias()
  {
    return singleAlias;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSingleAlias(SingleAlias newSingleAlias, NotificationChain msgs)
  {
    SingleAlias oldSingleAlias = singleAlias;
    singleAlias = newSingleAlias;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DslPackage.ALIAS__SINGLE_ALIAS, oldSingleAlias, newSingleAlias);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSingleAlias(SingleAlias newSingleAlias)
  {
    if (newSingleAlias != singleAlias)
    {
      NotificationChain msgs = null;
      if (singleAlias != null)
        msgs = ((InternalEObject)singleAlias).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DslPackage.ALIAS__SINGLE_ALIAS, null, msgs);
      if (newSingleAlias != null)
        msgs = ((InternalEObject)newSingleAlias).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DslPackage.ALIAS__SINGLE_ALIAS, null, msgs);
      msgs = basicSetSingleAlias(newSingleAlias, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.ALIAS__SINGLE_ALIAS, newSingleAlias, newSingleAlias));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DslPackage.ALIAS__LIST_OF_ALIASES:
        return basicSetListOfAliases(null, msgs);
      case DslPackage.ALIAS__SINGLE_ALIAS:
        return basicSetSingleAlias(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.ALIAS__NAME:
        return getName();
      case DslPackage.ALIAS__LIST_OF_ALIASES:
        return getListOfAliases();
      case DslPackage.ALIAS__SINGLE_ALIAS:
        return getSingleAlias();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.ALIAS__NAME:
        setName((String)newValue);
        return;
      case DslPackage.ALIAS__LIST_OF_ALIASES:
        setListOfAliases((AliasList)newValue);
        return;
      case DslPackage.ALIAS__SINGLE_ALIAS:
        setSingleAlias((SingleAlias)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.ALIAS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DslPackage.ALIAS__LIST_OF_ALIASES:
        setListOfAliases((AliasList)null);
        return;
      case DslPackage.ALIAS__SINGLE_ALIAS:
        setSingleAlias((SingleAlias)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.ALIAS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DslPackage.ALIAS__LIST_OF_ALIASES:
        return listOfAliases != null;
      case DslPackage.ALIAS__SINGLE_ALIAS:
        return singleAlias != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //AliasImpl
