/**
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Access Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.entitas.lang.dsl.AccessRule#getName <em>Name</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.AccessRule#getMatcherRule <em>Matcher Rule</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.AccessRule#getScope <em>Scope</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.AccessRule#getContextRef <em>Context Ref</em>}</li>
 * </ul>
 *
 * @see io.entitas.lang.dsl.DslPackage#getAccessRule()
 * @model
 * @generated
 */
public interface AccessRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.entitas.lang.dsl.DslPackage#getAccessRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.AccessRule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Matcher Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Matcher Rule</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Matcher Rule</em>' containment reference.
   * @see #setMatcherRule(MatcherRule)
   * @see io.entitas.lang.dsl.DslPackage#getAccessRule_MatcherRule()
   * @model containment="true"
   * @generated
   */
  MatcherRule getMatcherRule();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.AccessRule#getMatcherRule <em>Matcher Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Matcher Rule</em>' containment reference.
   * @see #getMatcherRule()
   * @generated
   */
  void setMatcherRule(MatcherRule value);

  /**
   * Returns the value of the '<em><b>Scope</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scope</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' containment reference.
   * @see #setScope(ContextScope)
   * @see io.entitas.lang.dsl.DslPackage#getAccessRule_Scope()
   * @model containment="true"
   * @generated
   */
  ContextScope getScope();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.AccessRule#getScope <em>Scope</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' containment reference.
   * @see #getScope()
   * @generated
   */
  void setScope(ContextScope value);

  /**
   * Returns the value of the '<em><b>Context Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Context Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context Ref</em>' reference.
   * @see #setContextRef(ContextId)
   * @see io.entitas.lang.dsl.DslPackage#getAccessRule_ContextRef()
   * @model
   * @generated
   */
  ContextId getContextRef();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.AccessRule#getContextRef <em>Context Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context Ref</em>' reference.
   * @see #getContextRef()
   * @generated
   */
  void setContextRef(ContextId value);

} // AccessRule
