/**
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alias Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.entitas.lang.dsl.AliasRule#getTarget <em>Target</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.AliasRule#getTypeAlias <em>Type Alias</em>}</li>
 * </ul>
 *
 * @see io.entitas.lang.dsl.DslPackage#getAliasRule()
 * @model
 * @generated
 */
public interface AliasRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(TargetId)
   * @see io.entitas.lang.dsl.DslPackage#getAliasRule_Target()
   * @model
   * @generated
   */
  TargetId getTarget();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.AliasRule#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(TargetId value);

  /**
   * Returns the value of the '<em><b>Type Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Alias</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Alias</em>' attribute.
   * @see #setTypeAlias(String)
   * @see io.entitas.lang.dsl.DslPackage#getAliasRule_TypeAlias()
   * @model
   * @generated
   */
  String getTypeAlias();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.AliasRule#getTypeAlias <em>Type Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Alias</em>' attribute.
   * @see #getTypeAlias()
   * @generated
   */
  void setTypeAlias(String value);

} // AliasRule
