/**
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.entitas.lang.dsl.Component#getName <em>Name</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.Component#getParameters <em>Parameters</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.Component#getScope <em>Scope</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.Component#getListOfProperties <em>List Of Properties</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.Component#getPropertyPrefix <em>Property Prefix</em>}</li>
 * </ul>
 *
 * @see io.entitas.lang.dsl.DslPackage#getComponent()
 * @model
 * @generated
 */
public interface Component extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.entitas.lang.dsl.DslPackage#getComponent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.Component#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' attribute list.
   * @see io.entitas.lang.dsl.DslPackage#getComponent_Parameters()
   * @model unique="false"
   * @generated
   */
  EList<String> getParameters();

  /**
   * Returns the value of the '<em><b>Scope</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scope</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' containment reference.
   * @see #setScope(ContextScopes)
   * @see io.entitas.lang.dsl.DslPackage#getComponent_Scope()
   * @model containment="true"
   * @generated
   */
  ContextScopes getScope();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.Component#getScope <em>Scope</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' containment reference.
   * @see #getScope()
   * @generated
   */
  void setScope(ContextScopes value);

  /**
   * Returns the value of the '<em><b>List Of Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List Of Properties</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Of Properties</em>' containment reference.
   * @see #setListOfProperties(PropertyList)
   * @see io.entitas.lang.dsl.DslPackage#getComponent_ListOfProperties()
   * @model containment="true"
   * @generated
   */
  PropertyList getListOfProperties();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.Component#getListOfProperties <em>List Of Properties</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Of Properties</em>' containment reference.
   * @see #getListOfProperties()
   * @generated
   */
  void setListOfProperties(PropertyList value);

  /**
   * Returns the value of the '<em><b>Property Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Property Prefix</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Prefix</em>' containment reference.
   * @see #setPropertyPrefix(PropertyPrefix)
   * @see io.entitas.lang.dsl.DslPackage#getComponent_PropertyPrefix()
   * @model containment="true"
   * @generated
   */
  PropertyPrefix getPropertyPrefix();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.Component#getPropertyPrefix <em>Property Prefix</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Prefix</em>' containment reference.
   * @see #getPropertyPrefix()
   * @generated
   */
  void setPropertyPrefix(PropertyPrefix value);

} // Component
