/**
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Scopes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.entitas.lang.dsl.ContextScopes#getReferences <em>References</em>}</li>
 * </ul>
 *
 * @see io.entitas.lang.dsl.DslPackage#getContextScopes()
 * @model
 * @generated
 */
public interface ContextScopes extends EObject
{
  /**
   * Returns the value of the '<em><b>References</b></em>' reference list.
   * The list contents are of type {@link io.entitas.lang.dsl.ContextId}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>References</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>References</em>' reference list.
   * @see io.entitas.lang.dsl.DslPackage#getContextScopes_References()
   * @model
   * @generated
   */
  EList<ContextId> getReferences();

} // ContextScopes
