/**
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Scope</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.entitas.lang.dsl.ContextScope#getReference <em>Reference</em>}</li>
 * </ul>
 *
 * @see io.entitas.lang.dsl.DslPackage#getContextScope()
 * @model
 * @generated
 */
public interface ContextScope extends EObject
{
  /**
   * Returns the value of the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reference</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' reference.
   * @see #setReference(ContextId)
   * @see io.entitas.lang.dsl.DslPackage#getContextScope_Reference()
   * @model
   * @generated
   */
  ContextId getReference();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.ContextScope#getReference <em>Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' reference.
   * @see #getReference()
   * @generated
   */
  void setReference(ContextId value);

} // ContextScope
