/**
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Id</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.entitas.lang.dsl.ContextId#getName <em>Name</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.ContextId#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see io.entitas.lang.dsl.DslPackage#getContextId()
 * @model
 * @generated
 */
public interface ContextId extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.entitas.lang.dsl.DslPackage#getContextId_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.ContextId#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' attribute list.
   * @see io.entitas.lang.dsl.DslPackage#getContextId_Parameters()
   * @model unique="false"
   * @generated
   */
  EList<String> getParameters();

} // ContextId
