/**
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see io.entitas.lang.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.entitas.io/lang/DSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = io.entitas.lang.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.RootImpl <em>Root</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.RootImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getRoot()
   * @generated
   */
  int ROOT = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__TARGET = 0;

  /**
   * The feature id for the '<em><b>Namespace</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__NAMESPACE = 1;

  /**
   * The feature id for the '<em><b>Context</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__CONTEXT = 2;

  /**
   * The feature id for the '<em><b>Type Aliases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__TYPE_ALIASES = 3;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__COMPONENTS = 4;

  /**
   * The feature id for the '<em><b>Systems</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__SYSTEMS = 5;

  /**
   * The number of structural features of the '<em>Root</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.TargetImpl <em>Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.TargetImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getTarget()
   * @generated
   */
  int TARGET = 1;

  /**
   * The feature id for the '<em><b>Ids</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__IDS = 0;

  /**
   * The number of structural features of the '<em>Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.TargetIdImpl <em>Target Id</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.TargetIdImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getTargetId()
   * @generated
   */
  int TARGET_ID = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_ID__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_ID__PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Version</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_ID__VERSION = 2;

  /**
   * The number of structural features of the '<em>Target Id</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_ID_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.TargetParameterImpl <em>Target Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.TargetParameterImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getTargetParameter()
   * @generated
   */
  int TARGET_PARAMETER = 3;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_PARAMETER__PATH = 0;

  /**
   * The number of structural features of the '<em>Target Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.VersionImpl <em>Version</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.VersionImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getVersion()
   * @generated
   */
  int VERSION = 4;

  /**
   * The feature id for the '<em><b>Major</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION__MAJOR = 0;

  /**
   * The feature id for the '<em><b>Minor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION__MINOR = 1;

  /**
   * The feature id for the '<em><b>Patch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION__PATCH = 2;

  /**
   * The number of structural features of the '<em>Version</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.NamespaceImpl <em>Namespace</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.NamespaceImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getNamespace()
   * @generated
   */
  int NAMESPACE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE__NAME = 0;

  /**
   * The number of structural features of the '<em>Namespace</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.ContextImpl <em>Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.ContextImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getContext()
   * @generated
   */
  int CONTEXT = 6;

  /**
   * The feature id for the '<em><b>Ids</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__IDS = 0;

  /**
   * The number of structural features of the '<em>Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.ContextIdImpl <em>Context Id</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.ContextIdImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getContextId()
   * @generated
   */
  int CONTEXT_ID = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_ID__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_ID__PARAMETERS = 1;

  /**
   * The number of structural features of the '<em>Context Id</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_ID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.AliasImpl <em>Alias</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.AliasImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getAlias()
   * @generated
   */
  int ALIAS = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS__NAME = 0;

  /**
   * The feature id for the '<em><b>List Of Aliases</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS__LIST_OF_ALIASES = 1;

  /**
   * The feature id for the '<em><b>Single Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS__SINGLE_ALIAS = 2;

  /**
   * The number of structural features of the '<em>Alias</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.AliasListImpl <em>Alias List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.AliasListImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getAliasList()
   * @generated
   */
  int ALIAS_LIST = 9;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_LIST__RULES = 0;

  /**
   * The number of structural features of the '<em>Alias List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.AliasRuleImpl <em>Alias Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.AliasRuleImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getAliasRule()
   * @generated
   */
  int ALIAS_RULE = 10;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_RULE__TARGET = 0;

  /**
   * The feature id for the '<em><b>Type Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_RULE__TYPE_ALIAS = 1;

  /**
   * The number of structural features of the '<em>Alias Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALIAS_RULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.SingleAliasImpl <em>Single Alias</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.SingleAliasImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getSingleAlias()
   * @generated
   */
  int SINGLE_ALIAS = 11;

  /**
   * The feature id for the '<em><b>Type Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_ALIAS__TYPE_ALIAS = 0;

  /**
   * The number of structural features of the '<em>Single Alias</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_ALIAS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.ComponentImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Scope</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__SCOPE = 2;

  /**
   * The feature id for the '<em><b>List Of Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__LIST_OF_PROPERTIES = 3;

  /**
   * The feature id for the '<em><b>Property Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__PROPERTY_PREFIX = 4;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.PropertyListImpl <em>Property List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.PropertyListImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getPropertyList()
   * @generated
   */
  int PROPERTY_LIST = 13;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_LIST__RULES = 0;

  /**
   * The number of structural features of the '<em>Property List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.PropertyRulesImpl <em>Property Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.PropertyRulesImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getPropertyRules()
   * @generated
   */
  int PROPERTY_RULES = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_RULES__NAME = 0;

  /**
   * The feature id for the '<em><b>Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_RULES__ALIAS = 1;

  /**
   * The number of structural features of the '<em>Property Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_RULES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.PropertyPrefixImpl <em>Property Prefix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.PropertyPrefixImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getPropertyPrefix()
   * @generated
   */
  int PROPERTY_PREFIX = 15;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_PREFIX__STRING = 0;

  /**
   * The number of structural features of the '<em>Property Prefix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_PREFIX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.ContextScopesImpl <em>Context Scopes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.ContextScopesImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getContextScopes()
   * @generated
   */
  int CONTEXT_SCOPES = 16;

  /**
   * The feature id for the '<em><b>References</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_SCOPES__REFERENCES = 0;

  /**
   * The number of structural features of the '<em>Context Scopes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_SCOPES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.SystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.SystemImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getSystem()
   * @generated
   */
  int SYSTEM = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Reactive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__REACTIVE = 2;

  /**
   * The feature id for the '<em><b>Scope</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__SCOPE = 3;

  /**
   * The feature id for the '<em><b>Trigger Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__TRIGGER_RULES = 4;

  /**
   * The feature id for the '<em><b>No Filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__NO_FILTER = 5;

  /**
   * The feature id for the '<em><b>Matcher Rules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__MATCHER_RULES = 6;

  /**
   * The feature id for the '<em><b>Access Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__ACCESS_RULES = 7;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.AccessRuleImpl <em>Access Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.AccessRuleImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getAccessRule()
   * @generated
   */
  int ACCESS_RULE = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCESS_RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Matcher Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCESS_RULE__MATCHER_RULE = 1;

  /**
   * The feature id for the '<em><b>Scope</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCESS_RULE__SCOPE = 2;

  /**
   * The feature id for the '<em><b>Context Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCESS_RULE__CONTEXT_REF = 3;

  /**
   * The number of structural features of the '<em>Access Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCESS_RULE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.TriggerRuleImpl <em>Trigger Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.TriggerRuleImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getTriggerRule()
   * @generated
   */
  int TRIGGER_RULE = 19;

  /**
   * The feature id for the '<em><b>Removed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_RULE__REMOVED = 0;

  /**
   * The feature id for the '<em><b>Added</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_RULE__ADDED = 1;

  /**
   * The feature id for the '<em><b>Removed Or Added</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_RULE__REMOVED_OR_ADDED = 2;

  /**
   * The feature id for the '<em><b>Components</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_RULE__COMPONENTS = 3;

  /**
   * The number of structural features of the '<em>Trigger Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_RULE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.MatcherRuleImpl <em>Matcher Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.MatcherRuleImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getMatcherRule()
   * @generated
   */
  int MATCHER_RULE = 20;

  /**
   * The feature id for the '<em><b>All Components</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCHER_RULE__ALL_COMPONENTS = 0;

  /**
   * The feature id for the '<em><b>Any Components</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCHER_RULE__ANY_COMPONENTS = 1;

  /**
   * The feature id for the '<em><b>None Components</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCHER_RULE__NONE_COMPONENTS = 2;

  /**
   * The number of structural features of the '<em>Matcher Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCHER_RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link io.entitas.lang.dsl.impl.ContextScopeImpl <em>Context Scope</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.entitas.lang.dsl.impl.ContextScopeImpl
   * @see io.entitas.lang.dsl.impl.DslPackageImpl#getContextScope()
   * @generated
   */
  int CONTEXT_SCOPE = 21;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_SCOPE__REFERENCE = 0;

  /**
   * The number of structural features of the '<em>Context Scope</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_SCOPE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.Root <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Root</em>'.
   * @see io.entitas.lang.dsl.Root
   * @generated
   */
  EClass getRoot();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.Root#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Target</em>'.
   * @see io.entitas.lang.dsl.Root#getTarget()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Target();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.Root#getNamespace <em>Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Namespace</em>'.
   * @see io.entitas.lang.dsl.Root#getNamespace()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Namespace();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.Root#getContext <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Context</em>'.
   * @see io.entitas.lang.dsl.Root#getContext()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Context();

  /**
   * Returns the meta object for the containment reference list '{@link io.entitas.lang.dsl.Root#getTypeAliases <em>Type Aliases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type Aliases</em>'.
   * @see io.entitas.lang.dsl.Root#getTypeAliases()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_TypeAliases();

  /**
   * Returns the meta object for the containment reference list '{@link io.entitas.lang.dsl.Root#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see io.entitas.lang.dsl.Root#getComponents()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Components();

  /**
   * Returns the meta object for the containment reference list '{@link io.entitas.lang.dsl.Root#getSystems <em>Systems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Systems</em>'.
   * @see io.entitas.lang.dsl.Root#getSystems()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Systems();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.Target <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target</em>'.
   * @see io.entitas.lang.dsl.Target
   * @generated
   */
  EClass getTarget();

  /**
   * Returns the meta object for the containment reference list '{@link io.entitas.lang.dsl.Target#getIds <em>Ids</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ids</em>'.
   * @see io.entitas.lang.dsl.Target#getIds()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Ids();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.TargetId <em>Target Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target Id</em>'.
   * @see io.entitas.lang.dsl.TargetId
   * @generated
   */
  EClass getTargetId();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.TargetId#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.entitas.lang.dsl.TargetId#getName()
   * @see #getTargetId()
   * @generated
   */
  EAttribute getTargetId_Name();

  /**
   * Returns the meta object for the containment reference list '{@link io.entitas.lang.dsl.TargetId#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see io.entitas.lang.dsl.TargetId#getParameters()
   * @see #getTargetId()
   * @generated
   */
  EReference getTargetId_Parameters();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.TargetId#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Version</em>'.
   * @see io.entitas.lang.dsl.TargetId#getVersion()
   * @see #getTargetId()
   * @generated
   */
  EReference getTargetId_Version();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.TargetParameter <em>Target Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target Parameter</em>'.
   * @see io.entitas.lang.dsl.TargetParameter
   * @generated
   */
  EClass getTargetParameter();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.TargetParameter#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see io.entitas.lang.dsl.TargetParameter#getPath()
   * @see #getTargetParameter()
   * @generated
   */
  EAttribute getTargetParameter_Path();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.Version <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Version</em>'.
   * @see io.entitas.lang.dsl.Version
   * @generated
   */
  EClass getVersion();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.Version#getMajor <em>Major</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Major</em>'.
   * @see io.entitas.lang.dsl.Version#getMajor()
   * @see #getVersion()
   * @generated
   */
  EAttribute getVersion_Major();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.Version#getMinor <em>Minor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Minor</em>'.
   * @see io.entitas.lang.dsl.Version#getMinor()
   * @see #getVersion()
   * @generated
   */
  EAttribute getVersion_Minor();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.Version#getPatch <em>Patch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Patch</em>'.
   * @see io.entitas.lang.dsl.Version#getPatch()
   * @see #getVersion()
   * @generated
   */
  EAttribute getVersion_Patch();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.Namespace <em>Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Namespace</em>'.
   * @see io.entitas.lang.dsl.Namespace
   * @generated
   */
  EClass getNamespace();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.Namespace#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.entitas.lang.dsl.Namespace#getName()
   * @see #getNamespace()
   * @generated
   */
  EAttribute getNamespace_Name();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.Context <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context</em>'.
   * @see io.entitas.lang.dsl.Context
   * @generated
   */
  EClass getContext();

  /**
   * Returns the meta object for the containment reference list '{@link io.entitas.lang.dsl.Context#getIds <em>Ids</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ids</em>'.
   * @see io.entitas.lang.dsl.Context#getIds()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Ids();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.ContextId <em>Context Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context Id</em>'.
   * @see io.entitas.lang.dsl.ContextId
   * @generated
   */
  EClass getContextId();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.ContextId#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.entitas.lang.dsl.ContextId#getName()
   * @see #getContextId()
   * @generated
   */
  EAttribute getContextId_Name();

  /**
   * Returns the meta object for the attribute list '{@link io.entitas.lang.dsl.ContextId#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parameters</em>'.
   * @see io.entitas.lang.dsl.ContextId#getParameters()
   * @see #getContextId()
   * @generated
   */
  EAttribute getContextId_Parameters();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.Alias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alias</em>'.
   * @see io.entitas.lang.dsl.Alias
   * @generated
   */
  EClass getAlias();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.Alias#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.entitas.lang.dsl.Alias#getName()
   * @see #getAlias()
   * @generated
   */
  EAttribute getAlias_Name();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.Alias#getListOfAliases <em>List Of Aliases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List Of Aliases</em>'.
   * @see io.entitas.lang.dsl.Alias#getListOfAliases()
   * @see #getAlias()
   * @generated
   */
  EReference getAlias_ListOfAliases();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.Alias#getSingleAlias <em>Single Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Single Alias</em>'.
   * @see io.entitas.lang.dsl.Alias#getSingleAlias()
   * @see #getAlias()
   * @generated
   */
  EReference getAlias_SingleAlias();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.AliasList <em>Alias List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alias List</em>'.
   * @see io.entitas.lang.dsl.AliasList
   * @generated
   */
  EClass getAliasList();

  /**
   * Returns the meta object for the containment reference list '{@link io.entitas.lang.dsl.AliasList#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see io.entitas.lang.dsl.AliasList#getRules()
   * @see #getAliasList()
   * @generated
   */
  EReference getAliasList_Rules();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.AliasRule <em>Alias Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alias Rule</em>'.
   * @see io.entitas.lang.dsl.AliasRule
   * @generated
   */
  EClass getAliasRule();

  /**
   * Returns the meta object for the reference '{@link io.entitas.lang.dsl.AliasRule#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see io.entitas.lang.dsl.AliasRule#getTarget()
   * @see #getAliasRule()
   * @generated
   */
  EReference getAliasRule_Target();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.AliasRule#getTypeAlias <em>Type Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Alias</em>'.
   * @see io.entitas.lang.dsl.AliasRule#getTypeAlias()
   * @see #getAliasRule()
   * @generated
   */
  EAttribute getAliasRule_TypeAlias();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.SingleAlias <em>Single Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Alias</em>'.
   * @see io.entitas.lang.dsl.SingleAlias
   * @generated
   */
  EClass getSingleAlias();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.SingleAlias#getTypeAlias <em>Type Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Alias</em>'.
   * @see io.entitas.lang.dsl.SingleAlias#getTypeAlias()
   * @see #getSingleAlias()
   * @generated
   */
  EAttribute getSingleAlias_TypeAlias();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see io.entitas.lang.dsl.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.Component#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.entitas.lang.dsl.Component#getName()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Name();

  /**
   * Returns the meta object for the attribute list '{@link io.entitas.lang.dsl.Component#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parameters</em>'.
   * @see io.entitas.lang.dsl.Component#getParameters()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Parameters();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.Component#getScope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Scope</em>'.
   * @see io.entitas.lang.dsl.Component#getScope()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Scope();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.Component#getListOfProperties <em>List Of Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List Of Properties</em>'.
   * @see io.entitas.lang.dsl.Component#getListOfProperties()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_ListOfProperties();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.Component#getPropertyPrefix <em>Property Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Property Prefix</em>'.
   * @see io.entitas.lang.dsl.Component#getPropertyPrefix()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_PropertyPrefix();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.PropertyList <em>Property List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property List</em>'.
   * @see io.entitas.lang.dsl.PropertyList
   * @generated
   */
  EClass getPropertyList();

  /**
   * Returns the meta object for the containment reference list '{@link io.entitas.lang.dsl.PropertyList#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see io.entitas.lang.dsl.PropertyList#getRules()
   * @see #getPropertyList()
   * @generated
   */
  EReference getPropertyList_Rules();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.PropertyRules <em>Property Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Rules</em>'.
   * @see io.entitas.lang.dsl.PropertyRules
   * @generated
   */
  EClass getPropertyRules();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.PropertyRules#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.entitas.lang.dsl.PropertyRules#getName()
   * @see #getPropertyRules()
   * @generated
   */
  EAttribute getPropertyRules_Name();

  /**
   * Returns the meta object for the reference '{@link io.entitas.lang.dsl.PropertyRules#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Alias</em>'.
   * @see io.entitas.lang.dsl.PropertyRules#getAlias()
   * @see #getPropertyRules()
   * @generated
   */
  EReference getPropertyRules_Alias();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.PropertyPrefix <em>Property Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Prefix</em>'.
   * @see io.entitas.lang.dsl.PropertyPrefix
   * @generated
   */
  EClass getPropertyPrefix();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.PropertyPrefix#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see io.entitas.lang.dsl.PropertyPrefix#getString()
   * @see #getPropertyPrefix()
   * @generated
   */
  EAttribute getPropertyPrefix_String();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.ContextScopes <em>Context Scopes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context Scopes</em>'.
   * @see io.entitas.lang.dsl.ContextScopes
   * @generated
   */
  EClass getContextScopes();

  /**
   * Returns the meta object for the reference list '{@link io.entitas.lang.dsl.ContextScopes#getReferences <em>References</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>References</em>'.
   * @see io.entitas.lang.dsl.ContextScopes#getReferences()
   * @see #getContextScopes()
   * @generated
   */
  EReference getContextScopes_References();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.System <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see io.entitas.lang.dsl.System
   * @generated
   */
  EClass getSystem();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.System#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.entitas.lang.dsl.System#getName()
   * @see #getSystem()
   * @generated
   */
  EAttribute getSystem_Name();

  /**
   * Returns the meta object for the attribute list '{@link io.entitas.lang.dsl.System#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parameters</em>'.
   * @see io.entitas.lang.dsl.System#getParameters()
   * @see #getSystem()
   * @generated
   */
  EAttribute getSystem_Parameters();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.System#isReactive <em>Reactive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reactive</em>'.
   * @see io.entitas.lang.dsl.System#isReactive()
   * @see #getSystem()
   * @generated
   */
  EAttribute getSystem_Reactive();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.System#getScope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Scope</em>'.
   * @see io.entitas.lang.dsl.System#getScope()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Scope();

  /**
   * Returns the meta object for the containment reference list '{@link io.entitas.lang.dsl.System#getTriggerRules <em>Trigger Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trigger Rules</em>'.
   * @see io.entitas.lang.dsl.System#getTriggerRules()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_TriggerRules();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.System#isNoFilter <em>No Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No Filter</em>'.
   * @see io.entitas.lang.dsl.System#isNoFilter()
   * @see #getSystem()
   * @generated
   */
  EAttribute getSystem_NoFilter();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.System#getMatcherRules <em>Matcher Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Matcher Rules</em>'.
   * @see io.entitas.lang.dsl.System#getMatcherRules()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_MatcherRules();

  /**
   * Returns the meta object for the containment reference list '{@link io.entitas.lang.dsl.System#getAccessRules <em>Access Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Access Rules</em>'.
   * @see io.entitas.lang.dsl.System#getAccessRules()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_AccessRules();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.AccessRule <em>Access Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Access Rule</em>'.
   * @see io.entitas.lang.dsl.AccessRule
   * @generated
   */
  EClass getAccessRule();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.AccessRule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.entitas.lang.dsl.AccessRule#getName()
   * @see #getAccessRule()
   * @generated
   */
  EAttribute getAccessRule_Name();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.AccessRule#getMatcherRule <em>Matcher Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Matcher Rule</em>'.
   * @see io.entitas.lang.dsl.AccessRule#getMatcherRule()
   * @see #getAccessRule()
   * @generated
   */
  EReference getAccessRule_MatcherRule();

  /**
   * Returns the meta object for the containment reference '{@link io.entitas.lang.dsl.AccessRule#getScope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Scope</em>'.
   * @see io.entitas.lang.dsl.AccessRule#getScope()
   * @see #getAccessRule()
   * @generated
   */
  EReference getAccessRule_Scope();

  /**
   * Returns the meta object for the reference '{@link io.entitas.lang.dsl.AccessRule#getContextRef <em>Context Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Context Ref</em>'.
   * @see io.entitas.lang.dsl.AccessRule#getContextRef()
   * @see #getAccessRule()
   * @generated
   */
  EReference getAccessRule_ContextRef();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.TriggerRule <em>Trigger Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger Rule</em>'.
   * @see io.entitas.lang.dsl.TriggerRule
   * @generated
   */
  EClass getTriggerRule();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.TriggerRule#isRemoved <em>Removed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Removed</em>'.
   * @see io.entitas.lang.dsl.TriggerRule#isRemoved()
   * @see #getTriggerRule()
   * @generated
   */
  EAttribute getTriggerRule_Removed();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.TriggerRule#isAdded <em>Added</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Added</em>'.
   * @see io.entitas.lang.dsl.TriggerRule#isAdded()
   * @see #getTriggerRule()
   * @generated
   */
  EAttribute getTriggerRule_Added();

  /**
   * Returns the meta object for the attribute '{@link io.entitas.lang.dsl.TriggerRule#isRemovedOrAdded <em>Removed Or Added</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Removed Or Added</em>'.
   * @see io.entitas.lang.dsl.TriggerRule#isRemovedOrAdded()
   * @see #getTriggerRule()
   * @generated
   */
  EAttribute getTriggerRule_RemovedOrAdded();

  /**
   * Returns the meta object for the reference list '{@link io.entitas.lang.dsl.TriggerRule#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Components</em>'.
   * @see io.entitas.lang.dsl.TriggerRule#getComponents()
   * @see #getTriggerRule()
   * @generated
   */
  EReference getTriggerRule_Components();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.MatcherRule <em>Matcher Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Matcher Rule</em>'.
   * @see io.entitas.lang.dsl.MatcherRule
   * @generated
   */
  EClass getMatcherRule();

  /**
   * Returns the meta object for the reference list '{@link io.entitas.lang.dsl.MatcherRule#getAllComponents <em>All Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>All Components</em>'.
   * @see io.entitas.lang.dsl.MatcherRule#getAllComponents()
   * @see #getMatcherRule()
   * @generated
   */
  EReference getMatcherRule_AllComponents();

  /**
   * Returns the meta object for the reference list '{@link io.entitas.lang.dsl.MatcherRule#getAnyComponents <em>Any Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Any Components</em>'.
   * @see io.entitas.lang.dsl.MatcherRule#getAnyComponents()
   * @see #getMatcherRule()
   * @generated
   */
  EReference getMatcherRule_AnyComponents();

  /**
   * Returns the meta object for the reference list '{@link io.entitas.lang.dsl.MatcherRule#getNoneComponents <em>None Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>None Components</em>'.
   * @see io.entitas.lang.dsl.MatcherRule#getNoneComponents()
   * @see #getMatcherRule()
   * @generated
   */
  EReference getMatcherRule_NoneComponents();

  /**
   * Returns the meta object for class '{@link io.entitas.lang.dsl.ContextScope <em>Context Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context Scope</em>'.
   * @see io.entitas.lang.dsl.ContextScope
   * @generated
   */
  EClass getContextScope();

  /**
   * Returns the meta object for the reference '{@link io.entitas.lang.dsl.ContextScope#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Reference</em>'.
   * @see io.entitas.lang.dsl.ContextScope#getReference()
   * @see #getContextScope()
   * @generated
   */
  EReference getContextScope_Reference();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.RootImpl <em>Root</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.RootImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getRoot()
     * @generated
     */
    EClass ROOT = eINSTANCE.getRoot();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__TARGET = eINSTANCE.getRoot_Target();

    /**
     * The meta object literal for the '<em><b>Namespace</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__NAMESPACE = eINSTANCE.getRoot_Namespace();

    /**
     * The meta object literal for the '<em><b>Context</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__CONTEXT = eINSTANCE.getRoot_Context();

    /**
     * The meta object literal for the '<em><b>Type Aliases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__TYPE_ALIASES = eINSTANCE.getRoot_TypeAliases();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__COMPONENTS = eINSTANCE.getRoot_Components();

    /**
     * The meta object literal for the '<em><b>Systems</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__SYSTEMS = eINSTANCE.getRoot_Systems();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.TargetImpl <em>Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.TargetImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getTarget()
     * @generated
     */
    EClass TARGET = eINSTANCE.getTarget();

    /**
     * The meta object literal for the '<em><b>Ids</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__IDS = eINSTANCE.getTarget_Ids();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.TargetIdImpl <em>Target Id</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.TargetIdImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getTargetId()
     * @generated
     */
    EClass TARGET_ID = eINSTANCE.getTargetId();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TARGET_ID__NAME = eINSTANCE.getTargetId_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET_ID__PARAMETERS = eINSTANCE.getTargetId_Parameters();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET_ID__VERSION = eINSTANCE.getTargetId_Version();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.TargetParameterImpl <em>Target Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.TargetParameterImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getTargetParameter()
     * @generated
     */
    EClass TARGET_PARAMETER = eINSTANCE.getTargetParameter();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TARGET_PARAMETER__PATH = eINSTANCE.getTargetParameter_Path();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.VersionImpl <em>Version</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.VersionImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getVersion()
     * @generated
     */
    EClass VERSION = eINSTANCE.getVersion();

    /**
     * The meta object literal for the '<em><b>Major</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERSION__MAJOR = eINSTANCE.getVersion_Major();

    /**
     * The meta object literal for the '<em><b>Minor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERSION__MINOR = eINSTANCE.getVersion_Minor();

    /**
     * The meta object literal for the '<em><b>Patch</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERSION__PATCH = eINSTANCE.getVersion_Patch();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.NamespaceImpl <em>Namespace</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.NamespaceImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getNamespace()
     * @generated
     */
    EClass NAMESPACE = eINSTANCE.getNamespace();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAMESPACE__NAME = eINSTANCE.getNamespace_Name();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.ContextImpl <em>Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.ContextImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getContext()
     * @generated
     */
    EClass CONTEXT = eINSTANCE.getContext();

    /**
     * The meta object literal for the '<em><b>Ids</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__IDS = eINSTANCE.getContext_Ids();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.ContextIdImpl <em>Context Id</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.ContextIdImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getContextId()
     * @generated
     */
    EClass CONTEXT_ID = eINSTANCE.getContextId();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT_ID__NAME = eINSTANCE.getContextId_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT_ID__PARAMETERS = eINSTANCE.getContextId_Parameters();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.AliasImpl <em>Alias</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.AliasImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getAlias()
     * @generated
     */
    EClass ALIAS = eINSTANCE.getAlias();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALIAS__NAME = eINSTANCE.getAlias_Name();

    /**
     * The meta object literal for the '<em><b>List Of Aliases</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALIAS__LIST_OF_ALIASES = eINSTANCE.getAlias_ListOfAliases();

    /**
     * The meta object literal for the '<em><b>Single Alias</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALIAS__SINGLE_ALIAS = eINSTANCE.getAlias_SingleAlias();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.AliasListImpl <em>Alias List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.AliasListImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getAliasList()
     * @generated
     */
    EClass ALIAS_LIST = eINSTANCE.getAliasList();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALIAS_LIST__RULES = eINSTANCE.getAliasList_Rules();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.AliasRuleImpl <em>Alias Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.AliasRuleImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getAliasRule()
     * @generated
     */
    EClass ALIAS_RULE = eINSTANCE.getAliasRule();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALIAS_RULE__TARGET = eINSTANCE.getAliasRule_Target();

    /**
     * The meta object literal for the '<em><b>Type Alias</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALIAS_RULE__TYPE_ALIAS = eINSTANCE.getAliasRule_TypeAlias();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.SingleAliasImpl <em>Single Alias</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.SingleAliasImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getSingleAlias()
     * @generated
     */
    EClass SINGLE_ALIAS = eINSTANCE.getSingleAlias();

    /**
     * The meta object literal for the '<em><b>Type Alias</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_ALIAS__TYPE_ALIAS = eINSTANCE.getSingleAlias_TypeAlias();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.ComponentImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__NAME = eINSTANCE.getComponent_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__PARAMETERS = eINSTANCE.getComponent_Parameters();

    /**
     * The meta object literal for the '<em><b>Scope</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__SCOPE = eINSTANCE.getComponent_Scope();

    /**
     * The meta object literal for the '<em><b>List Of Properties</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__LIST_OF_PROPERTIES = eINSTANCE.getComponent_ListOfProperties();

    /**
     * The meta object literal for the '<em><b>Property Prefix</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__PROPERTY_PREFIX = eINSTANCE.getComponent_PropertyPrefix();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.PropertyListImpl <em>Property List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.PropertyListImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getPropertyList()
     * @generated
     */
    EClass PROPERTY_LIST = eINSTANCE.getPropertyList();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_LIST__RULES = eINSTANCE.getPropertyList_Rules();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.PropertyRulesImpl <em>Property Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.PropertyRulesImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getPropertyRules()
     * @generated
     */
    EClass PROPERTY_RULES = eINSTANCE.getPropertyRules();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_RULES__NAME = eINSTANCE.getPropertyRules_Name();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_RULES__ALIAS = eINSTANCE.getPropertyRules_Alias();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.PropertyPrefixImpl <em>Property Prefix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.PropertyPrefixImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getPropertyPrefix()
     * @generated
     */
    EClass PROPERTY_PREFIX = eINSTANCE.getPropertyPrefix();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_PREFIX__STRING = eINSTANCE.getPropertyPrefix_String();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.ContextScopesImpl <em>Context Scopes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.ContextScopesImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getContextScopes()
     * @generated
     */
    EClass CONTEXT_SCOPES = eINSTANCE.getContextScopes();

    /**
     * The meta object literal for the '<em><b>References</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_SCOPES__REFERENCES = eINSTANCE.getContextScopes_References();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.SystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.SystemImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getSystem()
     * @generated
     */
    EClass SYSTEM = eINSTANCE.getSystem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM__NAME = eINSTANCE.getSystem_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM__PARAMETERS = eINSTANCE.getSystem_Parameters();

    /**
     * The meta object literal for the '<em><b>Reactive</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM__REACTIVE = eINSTANCE.getSystem_Reactive();

    /**
     * The meta object literal for the '<em><b>Scope</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__SCOPE = eINSTANCE.getSystem_Scope();

    /**
     * The meta object literal for the '<em><b>Trigger Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__TRIGGER_RULES = eINSTANCE.getSystem_TriggerRules();

    /**
     * The meta object literal for the '<em><b>No Filter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM__NO_FILTER = eINSTANCE.getSystem_NoFilter();

    /**
     * The meta object literal for the '<em><b>Matcher Rules</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__MATCHER_RULES = eINSTANCE.getSystem_MatcherRules();

    /**
     * The meta object literal for the '<em><b>Access Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__ACCESS_RULES = eINSTANCE.getSystem_AccessRules();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.AccessRuleImpl <em>Access Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.AccessRuleImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getAccessRule()
     * @generated
     */
    EClass ACCESS_RULE = eINSTANCE.getAccessRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACCESS_RULE__NAME = eINSTANCE.getAccessRule_Name();

    /**
     * The meta object literal for the '<em><b>Matcher Rule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACCESS_RULE__MATCHER_RULE = eINSTANCE.getAccessRule_MatcherRule();

    /**
     * The meta object literal for the '<em><b>Scope</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACCESS_RULE__SCOPE = eINSTANCE.getAccessRule_Scope();

    /**
     * The meta object literal for the '<em><b>Context Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACCESS_RULE__CONTEXT_REF = eINSTANCE.getAccessRule_ContextRef();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.TriggerRuleImpl <em>Trigger Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.TriggerRuleImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getTriggerRule()
     * @generated
     */
    EClass TRIGGER_RULE = eINSTANCE.getTriggerRule();

    /**
     * The meta object literal for the '<em><b>Removed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER_RULE__REMOVED = eINSTANCE.getTriggerRule_Removed();

    /**
     * The meta object literal for the '<em><b>Added</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER_RULE__ADDED = eINSTANCE.getTriggerRule_Added();

    /**
     * The meta object literal for the '<em><b>Removed Or Added</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER_RULE__REMOVED_OR_ADDED = eINSTANCE.getTriggerRule_RemovedOrAdded();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER_RULE__COMPONENTS = eINSTANCE.getTriggerRule_Components();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.MatcherRuleImpl <em>Matcher Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.MatcherRuleImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getMatcherRule()
     * @generated
     */
    EClass MATCHER_RULE = eINSTANCE.getMatcherRule();

    /**
     * The meta object literal for the '<em><b>All Components</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MATCHER_RULE__ALL_COMPONENTS = eINSTANCE.getMatcherRule_AllComponents();

    /**
     * The meta object literal for the '<em><b>Any Components</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MATCHER_RULE__ANY_COMPONENTS = eINSTANCE.getMatcherRule_AnyComponents();

    /**
     * The meta object literal for the '<em><b>None Components</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MATCHER_RULE__NONE_COMPONENTS = eINSTANCE.getMatcherRule_NoneComponents();

    /**
     * The meta object literal for the '{@link io.entitas.lang.dsl.impl.ContextScopeImpl <em>Context Scope</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.entitas.lang.dsl.impl.ContextScopeImpl
     * @see io.entitas.lang.dsl.impl.DslPackageImpl#getContextScope()
     * @generated
     */
    EClass CONTEXT_SCOPE = eINSTANCE.getContextScope();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_SCOPE__REFERENCE = eINSTANCE.getContextScope_Reference();

  }

} //DslPackage
