/**
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.entitas.lang.dsl.PropertyRules#getName <em>Name</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.PropertyRules#getAlias <em>Alias</em>}</li>
 * </ul>
 *
 * @see io.entitas.lang.dsl.DslPackage#getPropertyRules()
 * @model
 * @generated
 */
public interface PropertyRules extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.entitas.lang.dsl.DslPackage#getPropertyRules_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.PropertyRules#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Alias</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alias</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' reference.
   * @see #setAlias(Alias)
   * @see io.entitas.lang.dsl.DslPackage#getPropertyRules_Alias()
   * @model
   * @generated
   */
  Alias getAlias();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.PropertyRules#getAlias <em>Alias</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' reference.
   * @see #getAlias()
   * @generated
   */
  void setAlias(Alias value);

} // PropertyRules
