/**
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.entitas.lang.dsl.System#getName <em>Name</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.System#getParameters <em>Parameters</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.System#isReactive <em>Reactive</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.System#getScope <em>Scope</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.System#getTriggerRules <em>Trigger Rules</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.System#isNoFilter <em>No Filter</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.System#getMatcherRules <em>Matcher Rules</em>}</li>
 *   <li>{@link io.entitas.lang.dsl.System#getAccessRules <em>Access Rules</em>}</li>
 * </ul>
 *
 * @see io.entitas.lang.dsl.DslPackage#getSystem()
 * @model
 * @generated
 */
public interface System extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.entitas.lang.dsl.DslPackage#getSystem_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.System#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' attribute list.
   * @see io.entitas.lang.dsl.DslPackage#getSystem_Parameters()
   * @model unique="false"
   * @generated
   */
  EList<String> getParameters();

  /**
   * Returns the value of the '<em><b>Reactive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reactive</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactive</em>' attribute.
   * @see #setReactive(boolean)
   * @see io.entitas.lang.dsl.DslPackage#getSystem_Reactive()
   * @model
   * @generated
   */
  boolean isReactive();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.System#isReactive <em>Reactive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reactive</em>' attribute.
   * @see #isReactive()
   * @generated
   */
  void setReactive(boolean value);

  /**
   * Returns the value of the '<em><b>Scope</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scope</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' containment reference.
   * @see #setScope(ContextScope)
   * @see io.entitas.lang.dsl.DslPackage#getSystem_Scope()
   * @model containment="true"
   * @generated
   */
  ContextScope getScope();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.System#getScope <em>Scope</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' containment reference.
   * @see #getScope()
   * @generated
   */
  void setScope(ContextScope value);

  /**
   * Returns the value of the '<em><b>Trigger Rules</b></em>' containment reference list.
   * The list contents are of type {@link io.entitas.lang.dsl.TriggerRule}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trigger Rules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger Rules</em>' containment reference list.
   * @see io.entitas.lang.dsl.DslPackage#getSystem_TriggerRules()
   * @model containment="true"
   * @generated
   */
  EList<TriggerRule> getTriggerRules();

  /**
   * Returns the value of the '<em><b>No Filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>No Filter</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>No Filter</em>' attribute.
   * @see #setNoFilter(boolean)
   * @see io.entitas.lang.dsl.DslPackage#getSystem_NoFilter()
   * @model
   * @generated
   */
  boolean isNoFilter();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.System#isNoFilter <em>No Filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>No Filter</em>' attribute.
   * @see #isNoFilter()
   * @generated
   */
  void setNoFilter(boolean value);

  /**
   * Returns the value of the '<em><b>Matcher Rules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Matcher Rules</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Matcher Rules</em>' containment reference.
   * @see #setMatcherRules(MatcherRule)
   * @see io.entitas.lang.dsl.DslPackage#getSystem_MatcherRules()
   * @model containment="true"
   * @generated
   */
  MatcherRule getMatcherRules();

  /**
   * Sets the value of the '{@link io.entitas.lang.dsl.System#getMatcherRules <em>Matcher Rules</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Matcher Rules</em>' containment reference.
   * @see #getMatcherRules()
   * @generated
   */
  void setMatcherRules(MatcherRule value);

  /**
   * Returns the value of the '<em><b>Access Rules</b></em>' containment reference list.
   * The list contents are of type {@link io.entitas.lang.dsl.AccessRule}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Access Rules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Access Rules</em>' containment reference list.
   * @see io.entitas.lang.dsl.DslPackage#getSystem_AccessRules()
   * @model containment="true"
   * @generated
   */
  EList<AccessRule> getAccessRules();

} // System
