/*
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.ide

import com.google.inject.Guice
import io.entitas.lang.DSLRuntimeModule
import io.entitas.lang.DSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DSLIdeSetup extends DSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DSLRuntimeModule, new DSLIdeModule))
	}
	
}
