/*
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import io.entitas.lang.dsl.Root
import static extension io.entitas.lang.extensions.AliasExtensions.*

@RunWith(XtextRunner)
@InjectWith(DSLInjectorProvider)
class AliasExtensionTest {
	@Inject
	ParseHelper<Root> parseHelper
	
	@Test
	def void aliasTypeSingle() {
		val result = parseHelper.parse('''
			target A
			alias int : "int"
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
		
		Assert.assertEquals("int", result.typeAliases.get(0).typeName)
	}
	
	@Test
	def void aliasTypeMultiple() {
		val result = parseHelper.parse('''
			target A, B
			alias int 
				A : "int"
				B : "Integer"
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
		
		Assert.assertEquals(null, result.typeAliases.get(0).typeName)
		Assert.assertEquals("int", result.typeAliases.get(0).typeName("A"))
		Assert.assertEquals("Integer", result.typeAliases.get(0).typeName("B"))
	}
}
