/*
 * generated by Xtext 2.11.0
 */
package io.entitas.lang.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DSLUiModule extends AbstractDSLUiModule {
}
